In [115]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [116]:
df = pd.read_csv("/content/car_sales.csv")

In [117]:
# https://www.kaggle.com/datasets/missionjee/car-sales-report

#dataset link

In [118]:
df.head()

,Car_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
0,C_CND_000001,01-02-2022,Geraldine,Male,13500,Buddy Storbeck's Diesel Service Inc,Ford,Expedition,DoubleÂ Overhead Camshaft,Auto,Black,26000,06457-3834,SUV,8264678,Middletown
1,C_CND_000002,01-02-2022,Gia,Male,1480000,C & M Motors Inc,Dodge,Durango,DoubleÂ Overhead Camshaft,Auto,Black,19000,60504-7114,SUV,6848189,Aurora
2,C_CND_000003,01-02-2022,Gianna,Male,1035000,Capitol KIA,Cadillac,Eldorado,Overhead Camshaft,Manual,Red,31500,38701-8047,Passenger,7298798,Greenville
3,C_CND_000004,01-02-2022,Giselle,Male,13500,Chrysler of Tri-Cities,Toyota,Celica,Overhead Camshaft,Manual,Pale White,14000,99301-3882,SUV,6257557,Pasco
4,C_CND_000005,01-02-2022,Grace,Male,1465000,Chrysler Plymouth,Acura,TL,DoubleÂ Overhead Camshaft,Auto,Red,24500,53546-9427,Hatchback,7081483,Janesville

In [119]:
df.tail()

,Car_id,Date,Customer Name,Gender,Annual Income,Dealer_Name,Company,Model,Engine,Transmission,Color,Price ($),Dealer_No,Body Style,Phone,Dealer_Region
23901,C_CND_023902,12/31/2023,Martin,Male,13500,C & M Motors Inc,Plymouth,Voyager,Overhead Camshaft,Manual,Red,12000,60504-7114,Passenger,8583598,Pasco
23902,C_CND_023903,12/31/2023,Jimmy,Female,900000,Ryder Truck Rental and Leasing,Chevrolet,Prizm,DoubleÂ Overhead Camshaft,Auto,Black,16000,06457-3834,Hardtop,7914229,Middletown
23903,C_CND_023904,12/31/2023,Emma,Male,705000,Chrysler of Tri-Cities,BMW,328i,Overhead Camshaft,Manual,Red,21000,99301-3882,Sedan,7659127,Scottsdale
23904,C_CND_023905,12/31/2023,Victoire,Male,13500,Chrysler Plymouth,Chevrolet,Metro,DoubleÂ Overhead Camshaft,Auto,Black,31000,53546-9427,Passenger,6030764,Austin
23905,C_CND_023906,12/31/2023,Donovan,Male,1225000,Pars Auto Sales,Lexus,ES300,DoubleÂ Overhead Camshaft,Auto,Pale White,27500,38701-8047,Hardtop,7020564,Middletown

In [6]:
df.shape

(13042, 16)

### Data Prepration and Cleaning :

    
* Check Missing values
* Check Duplicates
* Check data type
* Check the number of unique values of each column
* Check statistics of data set

In [102]:
df.isna().sum()

Car_id           0
Date             0
Customer Name    1
Gender           0
Annual Income    0
Dealer_Name      0
Company          0
Model            0
Engine           0
Transmission     0
Color            0
Price ($)        0
Dealer_No        0
Body Style       0
Phone            0
Dealer_Region    0
dtype: int64

In [104]:
df.duplicated().sum()

0

In [105]:
df.dtypes

Car_id           object
Date             object
Customer Name    object
Gender           object
Annual Income     int64
Dealer_Name      object
Company          object
Model            object
Engine           object
Transmission     object
Color            object
Price ($)         int64
Dealer_No        object
Body Style       object
Phone             int64
Dealer_Region    object
dtype: object

In [111]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23906 entries, 0 to 23905
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_id         23906 non-null  object
 1   Date           23906 non-null  object
 2   Customer Name  23905 non-null  object
 3   Gender         23906 non-null  object
 4   Annual Income  23906 non-null  int64
 5   Dealer_Name    23906 non-null  object
 6   Company        23906 non-null  object
 7   Model          23906 non-null  object
 8   Engine         23906 non-null  object
 9   Transmission   23906 non-null  object
 10  Color          23906 non-null  object
 11  Price ($)      23906 non-null  int64
 12  Dealer_No      23906 non-null  object
 13  Body Style     23906 non-null  object
 14  Phone          23906 non-null  int64
 15  Dealer_Region  23906 non-null  object
dtypes: int64(3), object(13)
memory usage: 2.9+ MB

In [121]:
df.describe()

       Annual Income     Price ($)         Phone
count   2.390600e+04  23906.000000  2.390600e+04
mean    8.308403e+05  28090.247846  7.497741e+06
std     7.200064e+05  14788.687608  8.674920e+05
min     1.008000e+04   1200.000000  6.000101e+06
25%     3.860000e+05  18001.000000  6.746495e+06
50%     7.350000e+05  23000.000000  7.496198e+06
75%     1.175750e+06  34000.000000  8.248146e+06
max     1.120000e+07  85800.000000  8.999579e+06

In [14]:
df.columns

Index(['Car_id', 'Date', 'Customer Name', 'Gender', 'Annual Income',
       'Dealer_Name', 'Company', 'Model', 'Engine', 'Transmission', 'Color',
       'Price ($)', 'Dealer_No ', 'Body Style', 'Phone', 'Dealer_Region'],
      dtype='object')

* <center><h3> Rename column name </h3></center>

In [16]:
df.rename(columns={"Price ($)":"price", "Annual Income":"annual_income", 'Body Style':"body_style", 'Customer Name':'customer_name'}, inplace =True)

<center> <h2> 1. Sales Performance Analysis </h2> </center>

* What is the total revenue generated by each dealer?
* Which dealer has the highest number of sales?
* What is the average price of cars sold by each dealer?

In [38]:
#What is the total revenue generated by each dealer?

total_sales_by_dealer = df.groupby('Dealer_Name').agg(total_revenue = ("price",'sum'))

total_sales_by_dealer.sort_values(by ="total_revenue", ascending =False).total_revenue.nlargest(10)

Dealer_Name
Rabun Used Car Sales                               20169184.0
Progressive Shippers Cooperative Association No    19924288.0
Ryder Truck Rental and Leasing                     19705285.0
Race Car Help                                      19465434.0
Suburban Ford                                      19334465.0
U-Haul CO                                          19321192.0
Star Enterprises Inc                               19281518.0
Scrivener Performance Engineering                  19039575.0
Saab-Belle Dodge                                   19023447.0
Tri-State Mack Inc                                 18489971.0
Name: total_revenue, dtype: float64

In [46]:
#What is the average price of cars sold by each dealer?

average_car_price_sold =  df.groupby('Dealer_Name').agg(average_price = ("price",'mean'))
average_car_price_sold.sort_values('average_price', ascending =False).average_price.nlargest(10)

Dealer_Name
U-Haul CO                         28880.705531
Chrysler of Tri-Cities            28820.379822
Rabun Used Car Sales              28649.409091
Motor Vehicle Branch Office       28581.907514
Star Enterprises Inc              28522.955621
C & M Motors Inc                  28420.795389
Ryder Truck Rental and Leasing    28393.782421
Hatfield Volkswagen               28281.156627
Race Car Help                     28251.718433
Nebo Chevrolet                    28224.830946
Name: average_price, dtype: float64

In [47]:
#What is the average price of cars sold by each dealer?

average_car_price_sold =  df.groupby('Dealer_Name').agg(average_price = ("price",'mean'))
average_car_price_sold.average_price.nlargest(10)

Dealer_Name
U-Haul CO                         28880.705531
Chrysler of Tri-Cities            28820.379822
Rabun Used Car Sales              28649.409091
Motor Vehicle Branch Office       28581.907514
Star Enterprises Inc              28522.955621
C & M Motors Inc                  28420.795389
Ryder Truck Rental and Leasing    28393.782421
Hatfield Volkswagen               28281.156627
Race Car Help                     28251.718433
Nebo Chevrolet                    28224.830946
Name: average_price, dtype: float64

<center> <h2> 2.Customer Demographics and Behavior </h2> </center>

* What is the gender distribution of customers?
* What is the average annual income of customers?
* Which age group has the highest number of purchases?